### PR TITLE
Fixed login for nlziet

### PR DESCRIPTION
**Pull request by nazegnl**

### CODE REVIEW

**Comment by dut-iptv** [comment]
Currently the way I am pushing changes to the GitHub/Kodi repo does not allow for easy handling of Pull requests.

I will take your addition in consideration for the next version of the NLZiet addon.

**Comment by nazegnl** [comment]
> Currently the way I am pushing changes to the GitHub/Kodi repo does not allow for easy handling of Pull requests.
> 
> I will take your addition in consideration for the next version of the NLZiet addon.

I know but wanted to help out with some maintenance :)

**Comment by dut-iptv** [comment]
Any help is much appreciated.

I was able to test the URL you provided and got an initial valid response. I wasnt able to mimmick the complete login flow of the ios/android apps though. Using mitmproxy I was able to inspect the complete login flow but got stuck on the oauth secret which I extracted from the web based app in the past without problem, but the secret is different in the app and I was not able to find the oauth secret using tools such as APKtool

The webbased version of NLZiet has since moved from oauth 1.0 to openid and I am now trying to recreate that flow in the addon.

**Comment by dut-iptv** [comment]
Was able to make your suggestion work in .99

**Pull request closed without merging**
